# Lista de opções para o selectbox
lista_topicos = {
    ":blue[Music (parent topic)]": "/m/04rlf",
    ":blue[Christian music]": "/m/02mscn",
    ":blue[Classical music]": "/m/0ggq0m",
    ":blue[Country]": "/m/01lyv",
    ":blue[Electronic music]": "/m/02lkt",
    ":blue[Hip hop music]": "/m/0glt670",
    ":blue[Independent music]": "/m/05rwpb",
    ":blue[Jazz]": "/m/03_d0",
    ":blue[Music of Asia]": "/m/028sqc",
    ":blue[Music of Latin America]": "/m/0g293",
    ":blue[Pop music]": "/m/064t9",
    ":blue[Reggae]": "/m/06cqb",
    ":blue[Rhythm and blues]": "/m/06j6l",
    ":blue[Rock music]": "/m/06by7",
    ":blue[Soul music]": "/m/0gywn",

    ":green[Gaming (parent topic)]": "/m/0bzvm2",
    ":green[Action game]": "/m/025zzc",
    ":green[Action-adventure game]": "/m/02ntfj",
    ":green[Casual game]": "/m/0b1vjn",
    ":green[Music video game]": "/m/02hygl",
    ":green[Puzzle video game]": "/m/04q1x3q",
    ":green[Racing video game]": "/m/01sjng",
    ":green[Role-playing video game]": "/m/0403l3g",
    ":green[Simulation video game]": "/m/021bp2",
    ":green[Sports game]": "/m/022dc6",
    ":green[Strategy video game]": "/m/03hf_rm",

    ":orange[Sports (parent topic)]": "/m/06ntj",
    ":orange[American football]": "/m/0jm_",
    ":orange[Baseball]": "/m/018jz",
    ":orange[Basketball]": "/m/018w8",
    ":orange[Boxing]": "/m/01cgz",
    ":orange[Cricket]": "/m/09xp_",
    ":orange[Football]": "/m/02vx4",
    ":orange[Golf]": "/m/037hz",
    ":orange[Ice hockey]": "/m/03tmr",
    ":orange[Mixed martial arts]": "/m/01h7lh",
    ":orange[Motorsport]": "/m/0410tth",
    ":orange[Tennis]": "/m/07bs0",
    ":orange[Volleyball]": "/m/07_53",

    ":violet[Entertainment (parent topic)]": "/m/02jjt",
    ":violet[Humor]": "/m/09kqc",
    ":violet[Movies]": "/m/02vxn",
    ":violet[Performing arts]": "/m/05qjc",
    ":violet[Professional wrestling]": "/m/066wd",
    ":violet[TV shows]": "/m/0f2f9",

    ":gray[Lifestyle (parent topic)]": "/m/019_rr",
    ":gray[Fashion]": "/m/032tl",
    ":gray[Fitness]": "/m/027x7n",
    ":gray[Food]": "/m/02wbm",
    ":gray[Hobby]": "/m/03glg",
    ":gray[Pets]": "/m/068hy",
    ":gray[Physical attractiveness [Beauty]]": "/m/041xxh",
    ":gray[Technology]": "/m/07c1v",
    ":gray[Tourism]": "/m/07bxq",
    ":gray[Vehicles]": "/m/07yv9",

    "Society (parent topic)": "/m/098wr",
    "Business": "/m/09s1f",
    "Health": "/m/0kt51",
    "Military": "/m/01h6rj",
    "Politics": "/m/05qt0",
    "Religion": "/m/06bvp",

    ":rainbow[Knowledge]": "/m/01k8wb"

}

